version: '3.5'
services:
  frontend:
    build: 
      context: frontend
      dockerfile: .docker/Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  
  backend:
    build: 
      context: backend
      dockerfile: .docker/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:6032 # Set the port for the backend service
    ports:
      - 6032:6032 # Map the host port to the container port
